api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "2529e6217855ff8f54ce8f8c3cc3c8096997a5d68a018e23482dbc263cf9d4be"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.103.tar.gz"
    source_sha256 = "07d050b019f377faea1ddc7267f9c1b745ccd21e095c0a2eec446dfd0e1f948e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.103-any-stack-2529e621.tgz"
    version = "0.0.103"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "2f40196c6cbf6fade3885a19535cfbeedd18c2775ff1ae24ed9b0b9fad0342f6"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "7b4cf9b427214067b9c5b36b596df53e0f072bed0d2782b90cf5bceaba46f35b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.63-any-stack-2f40196c.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "2c13275928fb1b65397e01804b94e35c13ed107d5b784bd9817809940d3ccf78"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "eb457026d4ba473789c98e30f43ccbffc7247743310f67fae0fc43ac8dd5ecd8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.69-any-stack-2c132759.tgz"
    version = "0.0.69"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.103"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.69"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.103"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.63"
