api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "bb1745abcbd0ec6f9333d29c86dcc37b38e5c2f65a32a441e820cce03428147a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.154.tar.gz"
    source_sha256 = "b6df72d23b7a9df5ed277fa326525df9c9b7049671fa239542406d12e3d442ff"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.154-any-stack-bb1745ab.tgz"
    version = "0.0.154"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "b98c1988230e043b5d0618cd69bcff832da91a8f85eb532c4be688c26326f8a6"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "c2813997623a11ac5f3e9d4bf7f72040327befd9b86fe4e37471d1d785e60f82"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.92-any-stack-b98c1988.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "95fd9edf7cb3da41c076441895bc515cd0076970c49e35357bf084ac5fc8fb28"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "4e8e2443e4fc6986c3089c78ed7ef6f00078231bf5db5f0c382094cf4689c976"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.110-any-stack-95fd9edf.tgz"
    version = "0.0.110"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.154"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.110"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.154"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.92"
