api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "de6414b60eeb2920d5d6dcf27a96363ca319dfcff5de563e1c338816e52b90b4"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.141.tar.gz"
    source_sha256 = "b49effe3b296f0087a0cb3e380bd8f96b69a091954f36cc5df0bad5cb3a18c57"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.141-any-stack-de6414b6.tgz"
    version = "0.0.141"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "49a9ff6fd238a9f31ef02efe2a6233bca8775b262054b427ff9ee23e11215534"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "5f3d63351a02074e6cf0ebb8678be4f72405f9c39b5d2d20bf07a7ca0c1375ad"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.68-any-stack-49a9ff6f.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "5356dae96623b9a22c3887ec6af6f2e4938900f2477ccc0552a31c1376e99431"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "2441eb730affdaf623d4e4e7bcd4c79e04d14cb22e4c041f058dbc2dd983e005"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.86-any-stack-5356dae9.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "a47cc977e580035a53f690aa46f1793ec61b17a8e4c6bd68b7858c596a06d431"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.98.tar.gz"
    source_sha256 = "4b1051f5e02c019930d61c44c4a1bf5a0e4d4c12dbdf46aed7cfc07d09218b6d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.98-any-stack-a47cc977.tgz"
    version = "0.0.98"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.141"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.98"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.141"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.86"
