api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "fe616060aee70ccd5f7cfa83aca7f0adf5a55d6eae9599f317163fe90ed5ace0"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.177.tar.gz"
    source_sha256 = "0f1f93c7922cc25e0f1deffc0978b8e18d82cb390eb6adb63da6c1c6ad8a21cc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine_0.0.177_linux_noarch_any-stack_fe616060.tgz"
    version = "0.0.177"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "90f77a072e03c1fc2cfc7ca5342aed60a9fc2891fc4896af777400501b464aac"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.8.tar.gz"
    source_sha256 = "783ad767293cdd9056fab6365769d08edfc856039904576ff9762e340feab6ee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm_0.1.8_linux_noarch_any-stack_90f77a07.tgz"
    version = "0.1.8"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn-install"
    sha256 = "d6dc674b41bd94a30b315fc48ce8652f3fd356c4719c4749b03c505bee6ca356"
    source = "https://github.com/cloudfoundry/yarn-install-cnb/archive/v0.1.18.tar.gz"
    source_sha256 = "d7f62b747f95d6dcf5f04ba3dfdd8d71dd2250f0e11d104a1da6c618a2f00b58"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn-install/org.cloudfoundry.yarn-install_0.1.18_linux_noarch_any-stack_d6dc674b.tgz"
    version = "0.1.18"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.177"

  [[order.group]]
    id = "org.cloudfoundry.yarn-install"
    version = "0.1.18"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.177"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.8"
