api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "0b79a208d1ed0d479d934d02df5637e82d3c06b5a8a50e729851c9adbf7233d0"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.86.tar.gz"
source_sha256 = "c36424939504d49e9bc09a896f4e30bbe607524a641e62d88cbd336511ee75dd"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.86-any-stack-0b79a208.tgz"
version = "0.0.86"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "86a6f546534c850268e29dc4d763b553393a3fadf6e36896bfd152f97cbbf04f"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.53.tar.gz"
source_sha256 = "43b1b37c8f75cd32730f369a19dd830e00f9707b92381f02856f71505202861a"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.53-any-stack-86a6f546.tgz"
version = "0.0.53"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "3316c2fb88c0846a86d12cbb7165428d9307a968299250b44d7eabdc237b1491"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.59.tar.gz"
source_sha256 = "142b937a08a3a3b1f4f57194f7ac90a3eb2a8bee1f7804bb3475824dc5cacb62"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.59-any-stack-3316c2fb.tgz"
version = "0.0.59"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.86"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.59"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.86"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.53"
