api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "0b55bc3c4a78bf198b440534b49edc768b474f44bd2e8890671ddd3bc2585722"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.74.tar.gz"
source_sha256 = "8ee6b8152239e5a9eb814b1cb26ac80e08491da7a1c9a20a2f6ad9781e769a32"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.74-any-stack-0b55bc3c.tgz"
version = "0.0.74"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "f194a1998ea159529e5b925bdd5ecd7692fee1ea189cecd45913fcaddddf699f"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "29f14c48b09ef4138cda9280bb007b5af75c8f143464cb46183f2818d2b0e4d7"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.45-any-stack-f194a199.tgz"
version = "0.0.45"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "9516edf18e5c97f73e648dca661e9b1db961c1d318e667a539ab259d25e5d63c"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.51.tar.gz"
source_sha256 = "5e3be3a4dee94ae020fa79ea7cfa41881a7814f011af48301dfbe6a15b30b2b3"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.51-any-stack-9516edf1.tgz"
version = "0.0.51"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.74"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.51"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.74"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.45"
