api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "ffa0aec443a3b32308fbecb413f8c935883be4ae5b0836e725be7dbcf838fb24"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.62.tar.gz"
source_sha256 = "0c58c3e997f71f6325804196f33f7cba59ceb1ab13bd21c3d6486bf059fdd65f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.62-any-stack-ffa0aec4.tgz"
version = "0.0.62"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "aa41466a97f2bf8a0bc5affb150c8cc69e32f1925d7533b9219d7e1988806c09"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "2532396786fc93f2961a9e817552729d1c2aa483f78d7c3ec1d63c8c6dd4d5f5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.41-any-stack-aa41466a.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "3bcb5e2411f89e1fbceef88f2c7cd480952a066eaa92774c75ad674882c721f8"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "c8eaa16f12ffc4fb7a49a709adcc10e06579ba3b8706014a58ca0398b14275e5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.42-any-stack-3bcb5e24.tgz"
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.62"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.62"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.41"
