api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "e9bfb27905fb3b48799eb57d9764d427af2d0fb6fce47b89378eeeff529bf11f"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "f87d08b149377fe75fa533cbfa535a00a82397cd7c2ad10e9fd01dd8048eee7c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.104-any-stack-e9bfb279.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "d8b6445460e5d38c2eb1fffe521d246ffc57faac042b177fb5132211fa97b9bd"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "89e1e311465bd8c8665a185121458912a71744b5d3c233b008cdc8d8a47faa2f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.65-any-stack-d8b64454.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "b5141c8380b0a46fcaf5ad2556d95ed9e90ff20c1daf89eb7229a0f9e579eea0"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "89bdfdf4d09440a5a23b796ac0535c45bd68e4383574e7aa10e0676cd7a1ec30"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.71-any-stack-b5141c83.tgz"
    version = "0.0.71"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.104"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.71"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.104"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.65"
