api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "110beb9c8751fade550583d91c6019755a5a6a61aee3858eeadeec925943a316"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.61.tar.gz"
source_sha256 = "02ebdf7359060cafeb221a042254def33991c73c82fbc05f5ce781044b878861"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.61-any-stack-110beb9c.tgz"
version = "0.0.61"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "03d41f69b5458d5d0b4a16dfeac8448ce1b1fec42cf808609e78f06a6320a348"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.38.tar.gz"
source_sha256 = "5f25391e59ab9941540bbd3c0af5f3aa517d2a4db79098480c762bbd24e8c310"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.38-any-stack-03d41f69.tgz"
version = "0.0.38"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "df4bb8e8ac84004b3634f4a0d912966a2dc82ca53f65a7e1540160c49da0111f"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "294c99ef00b2850780458c07584ee3eafbced6c4e88280312e685a48da605c79"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.40-any-stack-df4bb8e8.tgz"
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.61"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.61"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.38"
