api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "lifecycle"
sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
source = "https://github.com/buildpack/lifecycle/releases/download/v0.5.0/lifecycle-v0.5.0%2Blinux.x86-64.tgz"
source_sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
version = "0.5.0"

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "33fed7aeb4f50ee66d44efb3fa0f78a2937c27a3698c89dfe5c450d3e4cf46aa"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.81.tar.gz"
source_sha256 = "a19d6da57a9c42aaf0d81e17681670c1c1227d4163f691aced1d2f6f7419e75d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.81-any-stack-33fed7ae.tgz"
version = "0.0.81"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "2dd364dec9bbe4d0fc5ea716ae35b0fec5f3170f426e2681ab577b7f3af29a50"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "81ce0e281f17ef14986da7db07c3b84774f767c595036ef911266ce9ef5d6497"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.49-any-stack-2dd364de.tgz"
version = "0.0.49"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "8508b9f16d3bcfc54a0ad076350f962d2f71a3a9644d8d3e6a8b3635fcbe994c"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.54.tar.gz"
source_sha256 = "8be9a6e7c62f2c94adc93f48a74c1f12bbad3fad122fd762bd07b5160b3ca971"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.54-any-stack-8508b9f1.tgz"
version = "0.0.54"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.81"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.54"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.81"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.49"
