api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "f2951687b007617a8f9b3391ac9bd892f5fd37681d5aebecd946edeb7de9964e"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "823b4d302349196633eede35830d87a422cd792f13417ca3cd66cfd744f30ce8"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.89-any-stack-f2951687.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "ee55d191fa09b40701c52547ef4f6c8747fd30a0b34ec23e9a2d4049d428c0dd"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "7406c11be18a3d2b948ed05f37ab0c4eaadd83176dad6bb5ab21a7570d6934e0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.97-any-stack-ee55d191.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "ee55d191fa09b40701c52547ef4f6c8747fd30a0b34ec23e9a2d4049d428c0dd"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "7406c11be18a3d2b948ed05f37ab0c4eaadd83176dad6bb5ab21a7570d6934e0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.97-any-stack-ee55d191.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "75a119b524d4ffabd470f3fe560e9e3f73cceacde110452a5929d0abcb7063e8"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "8df5f80b79e2792847f35f138490afa5b6af8b83a3425a3e53393a692a6d4afc"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.55-any-stack-75a119b5.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "8b30984fcc7500fefb38556347f5cb9aa4a10a6b13419f9f295f76668b2416a7"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "4b51d10b15455826af51ce928c564e65e0edaf5d9f1095c1ac65d201d0b060c0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.61-any-stack-8b30984f.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "8b30984fcc7500fefb38556347f5cb9aa4a10a6b13419f9f295f76668b2416a7"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "4b51d10b15455826af51ce928c564e65e0edaf5d9f1095c1ac65d201d0b060c0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.61-any-stack-8b30984f.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "b6151972c8d662683a7a5bfac357ee5ad55455d9729fada710b33dc8a0cb39e3"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "bc4a0dc4ba5d652f12f9b76aecef02cc6901c59aaf33d005d43868344153ecbc"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.61-any-stack-b6151972.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "4813d1e7cdcaafcd4b89d529a8d9b3f3a1f4f91d549b31f86863ba6a9dd2427f"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "595ec516d39a7e3aadc818a0ae6e542c31362422db9644424c4782c4275c3157"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.68-any-stack-4813d1e7.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "4813d1e7cdcaafcd4b89d529a8d9b3f3a1f4f91d549b31f86863ba6a9dd2427f"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "595ec516d39a7e3aadc818a0ae6e542c31362422db9644424c4782c4275c3157"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.68-any-stack-4813d1e7.tgz"
    version = "0.0.68"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.97"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.68"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.97"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.61"
