api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "736ecece0614012c3dc046548a55c13b7847b0134ae1fc9b86cdb4ce1b85a257"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "0bc77d35ca21cd64b86963e9ebb2ad3757f74088b5ae9ef24d9d1bd01b1559f0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.110-any-stack-736ecece.tgz"
    version = "0.0.110"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "994e004499123e793e1bc4424822e2148b3fc2051c59212d5ba01b253cfd8acd"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "29807544a95f06508dede5bc862637640de96ced07452b613149ab27646abb4c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.68-any-stack-994e0044.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "b6fe7022bf95bb751a0c921b7bc56471db237e5d959f526543738c15d2cdf851"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "e8c361b5a8687ffa8d1eaaa4c0dd6fa43953cb9eae888193ae58753639008bec"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.76-any-stack-b6fe7022.tgz"
    version = "0.0.76"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.110"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.76"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.110"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.68"
