api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "4fb7db79d3d905c8325c861c59e6c2a255f06282abdb6057cb193dfa88eea8d4"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.106.tar.gz"
    source_sha256 = "ac8b5439eb2f78e4bd2442ab3dab97f487ca94f39bf3e77c1f010b14c4de794c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.106-any-stack-4fb7db79.tgz"
    version = "0.0.106"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "5295eb1a32a23d2b0cfee8c3b173883013e7d2df0646cde64442903caedf233b"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "8e93f12b426871a910d7bdb7d415b1b5046c3da855f7566957d7d0935bd2467e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.66-any-stack-5295eb1a.tgz"
    version = "0.0.66"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "155e49f9f7b4932bcbaf165935f0e553d6c418261a2a51e7a8aaca8aeb89dbcd"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "4e02d4117599e185ba9f3315aebd4b0b2db1d7dba47fc2bf6e85686edc491692"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.72-any-stack-155e49f9.tgz"
    version = "0.0.72"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.106"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.72"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.106"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.66"
