api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "00e0e332828ca0f780fe62a3f29bd4e8854672135d55bf06075df97706bf0a73"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.131.tar.gz"
    source_sha256 = "b6150bcb6213b85a8d89491f5d516db568ca6afa21a2506116f77f9cf0780b75"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.131-any-stack-00e0e332.tgz"
    version = "0.0.131"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "49a9ff6fd238a9f31ef02efe2a6233bca8775b262054b427ff9ee23e11215534"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "5f3d63351a02074e6cf0ebb8678be4f72405f9c39b5d2d20bf07a7ca0c1375ad"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.68-any-stack-49a9ff6f.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "fdc5b1441e6791b266c07ce1273d1e965a18ab73ce21203586399410981a5f99"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "8d5deb7f3dbd117a4a053f0f4e5454602cfa681afd06815d0d00dd879c6fe47f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.81-any-stack-fdc5b144.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "8eba10a219ade07dcd3001e5a588920662725c713b4c980b9c3363406352c0e5"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "f64e5b1c5aa9ef3bde29cd2fc938b21c74262e9bc67dcf3857567e08b5aa9de6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.91-any-stack-8eba10a2.tgz"
    version = "0.0.91"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.131"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.91"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.131"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.81"
