api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "a66fc3019e23238133ab89fc36aa631d4b920ef95115e99cfb2f6c6b8c7d6ab8"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.111.tar.gz"
    source_sha256 = "048b9571ff269ddced66fd1ab539718c0af1cfd1d1a58d87fadd9036b312eee0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.111-any-stack-a66fc301.tgz"
    version = "0.0.111"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "994e004499123e793e1bc4424822e2148b3fc2051c59212d5ba01b253cfd8acd"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "29807544a95f06508dede5bc862637640de96ced07452b613149ab27646abb4c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.68-any-stack-994e0044.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "e46c9e0365824948e3ac0799b894f4fe123e4bd2a4cd161ab2ded7d3be5a4cd9"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "cd78a988e6713efa3c864170fe6884b401f9db2b8a99230ce11bb6df75311c09"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.77-any-stack-e46c9e03.tgz"
    version = "0.0.77"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.111"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.77"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.111"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.68"
