api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "f2951687b007617a8f9b3391ac9bd892f5fd37681d5aebecd946edeb7de9964e"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "823b4d302349196633eede35830d87a422cd792f13417ca3cd66cfd744f30ce8"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.89-any-stack-f2951687.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "fabedb875e1cebb3eed43ef1d8f5f2175ac399d7564d60f52cffc583eedf04e0"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "8962bb88eef6e74b95af6ef4f75ad25d3e82ecfd8771cc99fcf1b508bf1d1447"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.99-any-stack-fabedb87.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "fabedb875e1cebb3eed43ef1d8f5f2175ac399d7564d60f52cffc583eedf04e0"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "8962bb88eef6e74b95af6ef4f75ad25d3e82ecfd8771cc99fcf1b508bf1d1447"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.99-any-stack-fabedb87.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "75a119b524d4ffabd470f3fe560e9e3f73cceacde110452a5929d0abcb7063e8"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "8df5f80b79e2792847f35f138490afa5b6af8b83a3425a3e53393a692a6d4afc"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.55-any-stack-75a119b5.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "b5171dac26017b39032ee748b5d665217d215a933f3cd69bceedb5a942c52a39"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "60263496e7adfffe30149ba715ee361f8c10e64cf99556ca285186ebfd7b5ade"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.62-any-stack-b5171dac.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "b5171dac26017b39032ee748b5d665217d215a933f3cd69bceedb5a942c52a39"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "60263496e7adfffe30149ba715ee361f8c10e64cf99556ca285186ebfd7b5ade"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.62-any-stack-b5171dac.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "b6151972c8d662683a7a5bfac357ee5ad55455d9729fada710b33dc8a0cb39e3"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "bc4a0dc4ba5d652f12f9b76aecef02cc6901c59aaf33d005d43868344153ecbc"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.61-any-stack-b6151972.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "4813d1e7cdcaafcd4b89d529a8d9b3f3a1f4f91d549b31f86863ba6a9dd2427f"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "595ec516d39a7e3aadc818a0ae6e542c31362422db9644424c4782c4275c3157"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.68-any-stack-4813d1e7.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "4813d1e7cdcaafcd4b89d529a8d9b3f3a1f4f91d549b31f86863ba6a9dd2427f"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "595ec516d39a7e3aadc818a0ae6e542c31362422db9644424c4782c4275c3157"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.68-any-stack-4813d1e7.tgz"
    version = "0.0.68"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.99"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.68"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.99"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.62"
