api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "26fc58f77347bdb6a98373f8037a2fd8fd14634676a6f6017f5cddc4e33a728f"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "abbbdf8ed4664fd67cc9c296d12719887479af6c7ef5b7c17e4d62cfbaf6716f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.49-any-stack-26fc58f7.tgz"
version = "0.0.49"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "7cf7624621af8c5f0467cd95c990bc29fbb1a38d6e1847de7dcdf63668440b0b"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.32.tar.gz"
source_sha256 = "804703b70699bc0be458a3c65fa320b8e20666ac48b0da5eb0dd6dd04135d9f9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.32-any-stack-7cf76246.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "20dfe8af9b68008d538e3d70283f9b6e83d62a1220e56d33bed1f2da771c940b"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.28.tar.gz"
source_sha256 = "c4e5c5fc5d540050cf8c7dc4638d6072f9b80702c66bf6b6243b5fc92886ca84"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.28-any-stack-20dfe8af.tgz"
version = "0.0.28"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.28"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.32"
