api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "f2951687b007617a8f9b3391ac9bd892f5fd37681d5aebecd946edeb7de9964e"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "823b4d302349196633eede35830d87a422cd792f13417ca3cd66cfd744f30ce8"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.89-any-stack-f2951687.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "c35349bb2b7e7b0bfc6bae987f3045712ae7ff36291a21443a902f87e1f7b6c9"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "a42dfbc40cca2b5c4e16192dc0fd8e2b2cac46bec476304725eeb81b6cb44d81"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.90-any-stack-c35349bb.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "c35349bb2b7e7b0bfc6bae987f3045712ae7ff36291a21443a902f87e1f7b6c9"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "a42dfbc40cca2b5c4e16192dc0fd8e2b2cac46bec476304725eeb81b6cb44d81"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.90-any-stack-c35349bb.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "75a119b524d4ffabd470f3fe560e9e3f73cceacde110452a5929d0abcb7063e8"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "8df5f80b79e2792847f35f138490afa5b6af8b83a3425a3e53393a692a6d4afc"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.55-any-stack-75a119b5.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "96fd9bb139063d2012c9e316d6efb8badd371f53bec1cd06e1ae4c17d77b4193"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "bbd3fc72b6ab0b9e40cdcf6a064ba76f4c30d9433d2d1cad5647bf02a1044170"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.56-any-stack-96fd9bb1.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "96fd9bb139063d2012c9e316d6efb8badd371f53bec1cd06e1ae4c17d77b4193"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "bbd3fc72b6ab0b9e40cdcf6a064ba76f4c30d9433d2d1cad5647bf02a1044170"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.56-any-stack-96fd9bb1.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "b6151972c8d662683a7a5bfac357ee5ad55455d9729fada710b33dc8a0cb39e3"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "bc4a0dc4ba5d652f12f9b76aecef02cc6901c59aaf33d005d43868344153ecbc"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.61-any-stack-b6151972.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "96fd657f3cc160d4b85b19232a068aa5def89e00a2bb643eda821adad24226aa"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "7eb2000bde7385204ff6f21ac7fdb7c9ac33d57386a533f1e00e890ca4cf7b56"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.62-any-stack-96fd657f.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "96fd657f3cc160d4b85b19232a068aa5def89e00a2bb643eda821adad24226aa"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "7eb2000bde7385204ff6f21ac7fdb7c9ac33d57386a533f1e00e890ca4cf7b56"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.62-any-stack-96fd657f.tgz"
    version = "0.0.62"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.90"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.62"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.90"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.56"
