api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "0e0578f4a8e965054685eaa6863cea9bc959120ec8327780dbe264ea6f80794f"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.46.tar.gz"
source_sha256 = "7d727ae7852bb77cbb6cd490d0a2bd559d6d716a82d5d60b4e403cb766cc61de"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.46-any-stack-0e0578f4.tgz"
version = "0.0.46"

[[metadata.dependencies]]
id = "org.cloudfoundry.nodejs-compat"
sha256 = "925b6ca3e6d6e018d166a9bbb4ee2603c2ec75b6ae9e123496fa3e373fb75cb0"
source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.15.tar.gz"
source_sha256 = "8f2618dc81680a1e45d4918f31ac6b2e1229c1c79658eed7e59898af58ba2f41"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.15-any-stack-925b6ca3.tgz"
version = "0.0.15"

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs-compat"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.46"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.22"

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs-compat"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.46"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.27"
