api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "3728787d68a733337de5c19b68e6cccfec0fee84473dc4d7519cbc3918069404"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.57.tar.gz"
source_sha256 = "68d5749f6d8b5066c4d26d11f4060ab7c389b3a5c017ca5fb9750d4f8048fdaf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.57-any-stack-3728787d.tgz"
version = "0.0.57"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "4c92f32fe550b885f3688097c87c8e65c10985b6563c19fbefc4e2cb4cdfdade"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "49b890e97261b2ab2292891a15b67e88abfdeaa44d2c350829fc20f3c27f3c60"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.34-any-stack-4c92f32f.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "04612667135283ddae52d4a55c8ad819ca9a23eadfe99108262fe6e066e79549"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "006a1fd055858961733e5c58d4143179211cbecd66b53fdad645ddf70e572d83"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.36-any-stack-04612667.tgz"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.57"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.57"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.34"
