api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "40f5cefe3db9eaf2f38ae62dfad8eb091bde5cc3c8c76577c2acd732daf59004"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.115.tar.gz"
    source_sha256 = "4c5e9e121df4065300cc43050e1b01277269a88bed5c68207e7ab539ddd43fca"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.115-any-stack-40f5cefe.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "5147cf61cd33045eb94049643e13bb3ae82ddf63e2475b5b0f1a203ede7bd805"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "ee3fb3b7aed8f7e3c781e7c11515ae30d9ac537f41eba8108a982501f479261c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.71-any-stack-5147cf61.tgz"
    version = "0.0.71"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "361ea27f30973673df3b18d039eb4579c75210310d8e14ebb81e861a86bb389d"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "17b047b234ae79cfcfbe7e752ac1dbd9c792eba6d7b7b2f8dfaae2ae241a08ac"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.80-any-stack-361ea27f.tgz"
    version = "0.0.80"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.115"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.80"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.115"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.71"
