api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "f772eb9ffc0e59690dabb717523ffa8c05efa608981c33d731b32767ee9d6842"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.156.tar.gz"
    source_sha256 = "7e216f2b35704ded2f60fe63052511339897936282aac17f09ec73f9759a194d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.156-any-stack-f772eb9f.tgz"
    version = "0.0.156"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "648138974ca7f63b40dd15a2720d86e4b16105b445cc28d88067b72bd9add53d"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.2.tar.gz"
    source_sha256 = "4438587e1450a515a7842653a6d3aec0332d4bd51d1b4532039b26a266fe9470"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.1.2-any-stack-64813897.tgz"
    version = "0.1.2"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "8d4a9d253e0d0b0b963fd0708646d5c5eac19fd64b869f965cc89f2009b3ffdb"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.111.tar.gz"
    source_sha256 = "d8d2ef9f167e79eec6b923830f7861fd310e85ef9631991d804df7636b86e704"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.111-any-stack-8d4a9d25.tgz"
    version = "0.0.111"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.156"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.111"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.156"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.2"
