api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "0fa8bc9df07ae832e64bca082a4fb7293f7ae9dbb856302e251e8e2bf30e00c4"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.71.tar.gz"
source_sha256 = "f5dc4075da4b873a2604fbff136ebdadd55b355998f650334d9895556bcd89b4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.71-any-stack-0fa8bc9d.tgz"
version = "0.0.71"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "6ddfc2cff3db401ea11e1d1b22e2cee2cfc70bd3d4f111cef3e7769f440aa364"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.44.tar.gz"
source_sha256 = "ca89a412e7874d8ce2d59e1d76ed1e9de2eefb62b2a4f6dea3cf9c3d0a59b68d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.44-any-stack-6ddfc2cf.tgz"
version = "0.0.44"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "125ebd9badae444ad552800dab35acf15bc54c739f49fb380293d7fead925ff3"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "9fc670afa29e38524adc21a61723f02d16e45b1402b2f7609d9b2b919ca543ec"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.49-any-stack-125ebd9b.tgz"
version = "0.0.49"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.71"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.49"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.71"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.44"
