api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "7517c8be041eacdc874fe952cde38110e5d221165eaa2f3811a463fbe76ac6c7"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.0/lifecycle-v0.6.0%2Blinux.x86-64.tgz"
    source_sha256 = "7517c8be041eacdc874fe952cde38110e5d221165eaa2f3811a463fbe76ac6c7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.0-any-stack-7517c8be.tgz"
    version = "0.6.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "b3861b6f7d1c851d029262637801689f81ab0e09de06a0c3903ce60104528a8c"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.144.tar.gz"
    source_sha256 = "60a8409f3a00586cd6a747140735977628ceb1e32ed14ce25b4205ce476ad9ec"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.144-any-stack-b3861b6f.tgz"
    version = "0.0.144"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "49a9ff6fd238a9f31ef02efe2a6233bca8775b262054b427ff9ee23e11215534"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "5f3d63351a02074e6cf0ebb8678be4f72405f9c39b5d2d20bf07a7ca0c1375ad"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.68-any-stack-49a9ff6f.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "a4368d8840d295c28f91759976113f4a8d2f1704e41019f22bf92ac9bc460014"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "0d2d0e61ee51182b1faa08942c1394c850c28f3754a5ef5f18edbf36a04ad80d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.87-any-stack-a4368d88.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "1ffdfd07b4f85740033d8de4ab6f5b4f0043d43560d4c37f396a1b92dd75f9e5"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "1d28c727aaa378dab40ed31368b8a61bd22f28be830d644217920e3ca9e02048"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.99-any-stack-1ffdfd07.tgz"
    version = "0.0.99"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.144"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.99"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.144"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.87"
