api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "8ed24c9cba06d48cf831a2e7a3aab906cf9aea736c752cf1c03432d0d1ee226c"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "1798729d3feb550dda38f4c237f5924609fcf8b5edb55549d52ee5f4d9b99d2b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.107-any-stack-8ed24c9c.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "c2d51bace40b246af780b1fc26996ceaf53f14348a17b6fb49a431e59dea6f5d"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "a4cc33a4b8ea6c95363f137beb1c485d647abf9ed2ec6ce2677bc1e6a81bac24"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.67-any-stack-c2d51bac.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "859b76dcd498d6f622c5652f87b92a98f5061b829adf49cdc6d2e514697cb2d7"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "59f49ad44ae287639ce44e6c862367669868f72b62668e52a5eccaf58c069071"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.73-any-stack-859b76dc.tgz"
    version = "0.0.73"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.107"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.73"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.107"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.67"
