api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "f2951687b007617a8f9b3391ac9bd892f5fd37681d5aebecd946edeb7de9964e"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "823b4d302349196633eede35830d87a422cd792f13417ca3cd66cfd744f30ce8"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.89-any-stack-f2951687.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "cc4f4ec119c322057f4063d6e73d9cff354961e4b12915add6f01c7bb067aec0"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "2422e36a15fcfdfe8c0239a696e6ef19e061fdf4e8c0dfc2aa9beb1a17ce2ddf"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.92-any-stack-cc4f4ec1.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "cc4f4ec119c322057f4063d6e73d9cff354961e4b12915add6f01c7bb067aec0"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "2422e36a15fcfdfe8c0239a696e6ef19e061fdf4e8c0dfc2aa9beb1a17ce2ddf"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.92-any-stack-cc4f4ec1.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "75a119b524d4ffabd470f3fe560e9e3f73cceacde110452a5929d0abcb7063e8"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "8df5f80b79e2792847f35f138490afa5b6af8b83a3425a3e53393a692a6d4afc"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.55-any-stack-75a119b5.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "742df1de2bc78aad10fd10f2e8e566243e6f5bf7c0a0cd834ea13fa3723b297e"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "b40d9df0d477747cef1e43280f683fc113258b2561d609424b0e3c5e0295260a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.58-any-stack-742df1de.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "742df1de2bc78aad10fd10f2e8e566243e6f5bf7c0a0cd834ea13fa3723b297e"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "b40d9df0d477747cef1e43280f683fc113258b2561d609424b0e3c5e0295260a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.58-any-stack-742df1de.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "b6151972c8d662683a7a5bfac357ee5ad55455d9729fada710b33dc8a0cb39e3"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "bc4a0dc4ba5d652f12f9b76aecef02cc6901c59aaf33d005d43868344153ecbc"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.61-any-stack-b6151972.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "f4e6bf4b12b2e54c749c665165784c725cd10cba54741c1e63d479bebe19b560"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "0b18e6d2cf844b783ce6ba67926f4db39230312a02e27ec95d3108f28e8143bc"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.63-any-stack-f4e6bf4b.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "f4e6bf4b12b2e54c749c665165784c725cd10cba54741c1e63d479bebe19b560"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "0b18e6d2cf844b783ce6ba67926f4db39230312a02e27ec95d3108f28e8143bc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.63-any-stack-f4e6bf4b.tgz"
    version = "0.0.63"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.92"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.63"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.92"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.58"
