api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "4850f5e74f63820a477d5346974bece814125cbc581a2d473c5605a2bc0ffeda"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.66.tar.gz"
source_sha256 = "25daddbab1937e78f7f75c58a86ff63865020a5156afa291e513e80c30ceefa3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.66-any-stack-4850f5e7.tgz"
version = "0.0.66"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "aa41466a97f2bf8a0bc5affb150c8cc69e32f1925d7533b9219d7e1988806c09"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "2532396786fc93f2961a9e817552729d1c2aa483f78d7c3ec1d63c8c6dd4d5f5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.41-any-stack-aa41466a.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "86f7fd987054372fc2e8c59ce6b905e7f4ed96f6c6b62efb5dcaca1db7deb600"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "2b9eed02436aaa29483595d61ac0b26821bf7cdf1fc46fcdddd2dcd0c24aedf8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.47-any-stack-86f7fd98.tgz"
version = "0.0.47"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.66"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.47"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.66"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.41"
