api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "27bf03993087e289c53f605f4088851fe9632abce9df01078c50a10c678f2a19"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.73.tar.gz"
source_sha256 = "f0b67bc01bef953e453f8c7bcdcc94fe3cb23824d5c1f5aa79bbc8731be5e865"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.73-any-stack-27bf0399.tgz"
version = "0.0.73"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "6ddfc2cff3db401ea11e1d1b22e2cee2cfc70bd3d4f111cef3e7769f440aa364"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.44.tar.gz"
source_sha256 = "ca89a412e7874d8ce2d59e1d76ed1e9de2eefb62b2a4f6dea3cf9c3d0a59b68d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.44-any-stack-6ddfc2cf.tgz"
version = "0.0.44"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "9516edf18e5c97f73e648dca661e9b1db961c1d318e667a539ab259d25e5d63c"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.51.tar.gz"
source_sha256 = "5e3be3a4dee94ae020fa79ea7cfa41881a7814f011af48301dfbe6a15b30b2b3"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.51-any-stack-9516edf1.tgz"
version = "0.0.51"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.73"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.51"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.73"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.44"
