api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "ba2c83f60c68763fdea89100025da58e06b7ecd5345dfef23e556cb9993fdf0f"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.88.tar.gz"
source_sha256 = "b50cb1248a8e6ceb05738b94729d3a2896b698933fa3105ad48d78fbe73dd609"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.88-any-stack-ba2c83f6.tgz"
version = "0.0.88"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "75a119b524d4ffabd470f3fe560e9e3f73cceacde110452a5929d0abcb7063e8"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.55.tar.gz"
source_sha256 = "8df5f80b79e2792847f35f138490afa5b6af8b83a3425a3e53393a692a6d4afc"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.55-any-stack-75a119b5.tgz"
version = "0.0.55"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "b6151972c8d662683a7a5bfac357ee5ad55455d9729fada710b33dc8a0cb39e3"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.61.tar.gz"
source_sha256 = "bc4a0dc4ba5d652f12f9b76aecef02cc6901c59aaf33d005d43868344153ecbc"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.61-any-stack-b6151972.tgz"
version = "0.0.61"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.88"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.61"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.88"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.55"
