api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[[order]]
group = [
  { id = "org.cloudfoundry.nodejs-compat", version = "0.0.12", optional = true },
  { id = "org.cloudfoundry.node-engine", version = "0.0.43" },
  { id = "org.cloudfoundry.yarn", version = "0.0.22" }
]

[[order]]
group = [
  { id = "org.cloudfoundry.nodejs-compat", version = "0.0.12", optional = true },
  { id = "org.cloudfoundry.node-engine", version = "0.0.43" },
  { id = "org.cloudfoundry.npm", version = "0.0.27" }
]
