api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "48bb3c7bd9acbadbcb1c1283230768ad6271eca5a9fe7cc9e91e3b8c23aeaba4"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.58.tar.gz"
source_sha256 = "e7fc5459e1f50cac42eb8b4ae53fca73123da9f71c5b409c9281f0507567529b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.58-any-stack-48bb3c7b.tgz"
version = "0.0.58"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "c25ef4298483e2db6718f7acbcbc2a00671799719a7d030a286970b74de0d394"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.35.tar.gz"
source_sha256 = "8b543c24b9d124404a06948f6b6de86ef91f62af87feebf131fa440d89a544a0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.35-any-stack-c25ef429.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "863b1093f5515e3fc9b359bef42da469741440677db5e5a5807f101f8aa8fc5e"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "b159e113dd5c772237106ee62526be2a36ecb73f4687908e8bc3dfce77aeeb61"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.37-any-stack-863b1093.tgz"
version = "0.0.37"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.58"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.37"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.58"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.35"
