api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "fa001b4868862484f1321bd474aa2e0065244a606fe19e5043296f480a631ee5"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.120.tar.gz"
    source_sha256 = "ffc8d95fe41c5db93c166a696e52d3766c929682986888cae02f908a93e9ea72"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.120-any-stack-fa001b48.tgz"
    version = "0.0.120"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "05d86bba98b5e4cf268196b68bb3822e62552afc6d3310376fda7e85907e017d"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "88a13c43f1e8f19f8dc28b08c6f1e72ee229da29d7fee4002fa1b63de1a06975"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.73-any-stack-05d86bba.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "bdd0475ad5a1875f4552d6039cc73414af68d220404860a1975227e7c14d4458"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "5bab9a49dbd0e40c79159ebd98c924f0ac14384e6f7c2206150ae35e3c6a8b89"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.81-any-stack-bdd0475a.tgz"
    version = "0.0.81"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.120"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.81"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.120"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.73"
