api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "lifecycle"
sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
source = "https://github.com/buildpack/lifecycle/releases/download/v0.5.0/lifecycle-v0.5.0%2Blinux.x86-64.tgz"
source_sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
version = "0.5.0"

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "33fed7aeb4f50ee66d44efb3fa0f78a2937c27a3698c89dfe5c450d3e4cf46aa"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.81.tar.gz"
source_sha256 = "a19d6da57a9c42aaf0d81e17681670c1c1227d4163f691aced1d2f6f7419e75d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.81-any-stack-33fed7ae.tgz"
version = "0.0.81"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "ed082af1b246ec91814a9eb0c3a22cfc48cdfe42979e6ba88b6ba042fc153b93"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.50.tar.gz"
source_sha256 = "0de45ef691d23088681b9e97e715282b4a86640f0b067366804222c3d4cd679b"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.50-any-stack-ed082af1.tgz"
version = "0.0.50"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "f7e511ccef126a7c20bca1986d41426ee5285c0e1b0770c1ab416b09c9a90032"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.56.tar.gz"
source_sha256 = "413e421a5608701b9e7c6beb5766953033a5a1b7618a086d43e69c797755118f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.56-any-stack-f7e511cc.tgz"
version = "0.0.56"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.81"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.56"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.81"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.50"
