api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "4a99f6d5a2ec4d0ec71b09bebc89f4ec936ce512dfcec4257c2a1fc618470d9c"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.132.tar.gz"
    source_sha256 = "91eabc098cab690e45411904239b4a0417fe76a7396b251020b35c0ffe387ca9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.132-any-stack-4a99f6d5.tgz"
    version = "0.0.132"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "49a9ff6fd238a9f31ef02efe2a6233bca8775b262054b427ff9ee23e11215534"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "5f3d63351a02074e6cf0ebb8678be4f72405f9c39b5d2d20bf07a7ca0c1375ad"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.68-any-stack-49a9ff6f.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "7d2a1ea1743a00cb85009be3731b291da31ea8c55d01ae477b4497071d5e1b62"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "86fbd82aaaf180d86dfbef8eae0344298d95c9715c3b6144386db1904ade9672"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.82-any-stack-7d2a1ea1.tgz"
    version = "0.0.82"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "1c3f4a5a284e65667ff2b5206941618646863d133e69ddac52f924cac45281a3"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "2529113c24bbd84e06891b4b6a36841dc8e031fdae267daa7c1466c80101727c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.93-any-stack-1c3f4a5a.tgz"
    version = "0.0.93"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.132"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.93"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.132"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.82"
