api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]
metabuildpack = true

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "26fc58f77347bdb6a98373f8037a2fd8fd14634676a6f6017f5cddc4e33a728f"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "abbbdf8ed4664fd67cc9c296d12719887479af6c7ef5b7c17e4d62cfbaf6716f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.49-any-stack-26fc58f7.tgz"
version = "0.0.49"

[[metadata.dependencies]]
id = "org.cloudfoundry.nodejs-compat"
sha256 = "1b09df16f36c5f5b21857beb4428c41f98c5a10b11b39ff7a1fa0fb5ad28433c"
source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.17.tar.gz"
source_sha256 = "bc75498158ea9924664d096f342179e824b9e010533c567999ee79d8cb0c96b0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.17-any-stack-1b09df16.tgz"
version = "0.0.17"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "a223ff1aafebe6b2098b115b4b59e29aedf0063311ca8169f12c9c4940251d03"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.30.tar.gz"
source_sha256 = "d0ade5663724bdfe21cb4ffef27aa21c5af2d44ffc4159018181d38be213a2cf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.30-any-stack-a223ff1a.tgz"
version = "0.0.30"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "3c7d37cc7bed53aaa787ca43c57ab8bd074ba7b3834bf44bd21c1be53aada85d"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.26.tar.gz"
source_sha256 = "3c2897f6ec7212690810335de56f687810c0f3f3295eacf33945763f5f8c5a0a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.26-any-stack-3c7d37cc.tgz"
version = "0.0.26"

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs-compat"
optional = true
version = "0.0.17"

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.26"

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs-compat"
optional = true
version = "0.0.17"

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.30"
