api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "48bb3c7bd9acbadbcb1c1283230768ad6271eca5a9fe7cc9e91e3b8c23aeaba4"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.58.tar.gz"
source_sha256 = "e7fc5459e1f50cac42eb8b4ae53fca73123da9f71c5b409c9281f0507567529b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.58-any-stack-48bb3c7b.tgz"
version = "0.0.58"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "e84f066a2f5d3c330ef7272d764401b5a652c57ce585128ffa204f71f10a7c6c"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "0929b2f89e4c42eb482abf7079e7677a88fd6721d7e520b65125049c86a003fa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.36-any-stack-e84f066a.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "ed4a0f6426b08407deaec45e056305b73538d77511e38003e0f7d700f78c7787"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.38.tar.gz"
source_sha256 = "baf196463efc849e5c49ffb9f3b9158bfcaf534dbdc6914193ba1c000f3a28f5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.38-any-stack-ed4a0f64.tgz"
version = "0.0.38"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.58"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.38"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.58"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.36"
