api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "5abc450423b9a13cf3e8f83623d30cd61081af293e85044a8d6d88e29548cc66"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.7.2/lifecycle-v0.7.2%2Blinux.x86-64.tgz"
    source_sha256 = "5abc450423b9a13cf3e8f83623d30cd61081af293e85044a8d6d88e29548cc66"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.7.2-any-stack-5abc4504.tgz"
    version = "0.7.2"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "8ecb8e77ec16ede6d00b2707480e9ac92baf20f39c7429763e5967130dc78fec"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.173.tar.gz"
    source_sha256 = "27873219481b662bab7bcd961e0ff9cccd84ac7fba79aef92b76867b104b0159"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine_0.0.173_linux_noarch_any-stack_8ecb8e77.tgz"
    version = "0.0.173"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "d55cfa10fb8f08055076b1474150ba23d4ab1ed544ad451b13cdfe40a5103a6b"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.7.tar.gz"
    source_sha256 = "35f4e523d787300a130b3e192566222980f1d1a3cd9de8a2f2d13d2f58972c3e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm_0.1.7_linux_noarch_any-stack_d55cfa10.tgz"
    version = "0.1.7"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn-install"
    sha256 = "a00b905eae55f54b68e5ff764f2c27a602fd480daa53d04f61c4f2f4bdf78a6a"
    source = "https://github.com/cloudfoundry/yarn-install-cnb/archive/v0.1.15.tar.gz"
    source_sha256 = "5040e7ec7f2c3532382c254750fc8897183b80b90f9a57ed8bfb3ce60cf0d0e4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn-install/org.cloudfoundry.yarn-install_0.1.15_linux_noarch_any-stack_a00b905e.tgz"
    version = "0.1.15"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.173"

  [[order.group]]
    id = "org.cloudfoundry.yarn-install"
    version = "0.1.15"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.173"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.7"
