api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "cda811ab0d193b8308222f3be281932d993631635b1b91f4cc7bcdf83ae35ef4"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.126.tar.gz"
    source_sha256 = "1c5cd73f6463b1e5d5c8ffa5db975194471279c5a84c014e4eb901f72e461601"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.126-any-stack-cda811ab.tgz"
    version = "0.0.126"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "49a9ff6fd238a9f31ef02efe2a6233bca8775b262054b427ff9ee23e11215534"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "5f3d63351a02074e6cf0ebb8678be4f72405f9c39b5d2d20bf07a7ca0c1375ad"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.68-any-stack-49a9ff6f.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "8a2b2e9e23eeb373308fd61b12d6bdc1d74dc536428ceef7883e7780b70d1e3d"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "c0a0962e6963ac5fd759561d469191ed1230e851c8de40857544daf89040a167"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.77-any-stack-8a2b2e9e.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "78d41b418d7422e0560475205016c5a7c6faa4eb4cf9dd2b02fc4945ab9060a3"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "23b7db53b94cb977de1362851411515c3c61da8b265ef99df8baa2f0c2ca566d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.88-any-stack-78d41b41.tgz"
    version = "0.0.88"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.126"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.88"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.126"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.77"
