api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "ccbf755c43949fc347c1e4fc6cb5713542dfef89d84bfc073d6c89fc4920dc52"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.7.1/lifecycle-v0.7.1%2Blinux.x86-64.tgz"
    source_sha256 = "ccbf755c43949fc347c1e4fc6cb5713542dfef89d84bfc073d6c89fc4920dc52"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.7.1-any-stack-ccbf755c.tgz"
    version = "0.7.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "2c3dd2e41b37b85e540bf914533a594e2ea6529523abc7393ee91b4ac9fe3998"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.166.tar.gz"
    source_sha256 = "b1739d4946b2d2a1fbdfa40bb389dfb3930d11b3e318cd0b5901287c052b4aba"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.166-any-stack-2c3dd2e4.tgz"
    version = "0.0.166"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "820f9023f5f2f043bdc9837bc85b9e81d1b18747c92c03776cf4d57c5ed042f7"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.3.tar.gz"
    source_sha256 = "56caea3405b1ab055cf1b43a393fdf6c0949d8f0191d0972410bab8cc1a8cc81"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.1.3-any-stack-820f9023.tgz"
    version = "0.1.3"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn-install"
    sha256 = "91255d8356c733c8745c9c00e61ea0510c1c3a36a0f53efcdf33b7c56be07ccb"
    source = "https://github.com/cloudfoundry/yarn-install-cnb/archive/v0.1.10.tar.gz"
    source_sha256 = "9f30cf2be630dc2b2e1aab2ec1b7956cb9e5b30d721eb0df22761aee8ae1f9a0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn-install/org.cloudfoundry.yarn-install-0.1.10-any-stack-91255d83.tgz"
    version = "0.1.10"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.166"

  [[order.group]]
    id = "org.cloudfoundry.yarn-install"
    version = "0.1.10"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.166"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.3"
