api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "5abc450423b9a13cf3e8f83623d30cd61081af293e85044a8d6d88e29548cc66"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.7.2/lifecycle-v0.7.2%2Blinux.x86-64.tgz"
    source_sha256 = "5abc450423b9a13cf3e8f83623d30cd61081af293e85044a8d6d88e29548cc66"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.7.2-any-stack-5abc4504.tgz"
    version = "0.7.2"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "630e85979cec22e3e4662aa996ece2e7cbe704d1cc8eddcc6cf3209efa590336"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.169.tar.gz"
    source_sha256 = "b7e3fdbb73b6fd3ccd2fdf05249206d2870b85b3b9ae4d6274d203f01afab8bc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.169-any-stack-630e8597.tgz"
    version = "0.0.169"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "63b86a391f05beaf24b56cb399a1f09bc2f9beb924745668058fd84701ddacb9"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.4.tar.gz"
    source_sha256 = "8141b99715610cd86f65f4434ef68e63ad147a6d8b6119a1ad01672c1b1b824e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.1.4-any-stack-63b86a39.tgz"
    version = "0.1.4"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn-install"
    sha256 = "c684d96b409be575667a7d26efc82d918fd6b072b3a85b858ccd9fca13717736"
    source = "https://github.com/cloudfoundry/yarn-install-cnb/archive/v0.1.12.tar.gz"
    source_sha256 = "62546e14edf7357f580a0256d17da9d877bff0e952421f2418dd9a10927e6c75"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn-install/org.cloudfoundry.yarn-install-0.1.12-any-stack-c684d96b.tgz"
    version = "0.1.12"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.169"

  [[order.group]]
    id = "org.cloudfoundry.yarn-install"
    version = "0.1.12"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.169"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.4"
