api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

   [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "7a4319d9afd68c25b4d213a7fe0e5118eea6fa735939c62029acc6ed16f24e21"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.176.tar.gz"
    source_sha256 = "be910ca63de2892d3da432b58031e339c3e6d263d4ef8bfc988d4a4fda95a043"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine_0.0.176_linux_noarch_any-stack_7a4319d9.tgz"
    version = "0.0.176"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "90f77a072e03c1fc2cfc7ca5342aed60a9fc2891fc4896af777400501b464aac"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.8.tar.gz"
    source_sha256 = "783ad767293cdd9056fab6365769d08edfc856039904576ff9762e340feab6ee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm_0.1.8_linux_noarch_any-stack_90f77a07.tgz"
    version = "0.1.8"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn-install"
    sha256 = "077c2cb099bd963475fbfb24273c97ebfe01f28247e6e07c6ace63a09a49d9d1"
    source = "https://github.com/cloudfoundry/yarn-install-cnb/archive/v0.1.16.tar.gz"
    source_sha256 = "456ff68c03c65110e57a64c243f6a13d449b661593e0ad85c8e6c8bbebeb9988"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn-install/org.cloudfoundry.yarn-install_0.1.16_linux_noarch_any-stack_077c2cb0.tgz"
    version = "0.1.16"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.176"

  [[order.group]]
    id = "org.cloudfoundry.yarn-install"
    version = "0.1.16"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.176"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.8"
