api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "ba2c83f60c68763fdea89100025da58e06b7ecd5345dfef23e556cb9993fdf0f"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.88.tar.gz"
source_sha256 = "b50cb1248a8e6ceb05738b94729d3a2896b698933fa3105ad48d78fbe73dd609"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.88-any-stack-ba2c83f6.tgz"
version = "0.0.88"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "57bf29a66c862a9e3651a8af39d034ce26d4266ca186ec338d724cfec8c15a99"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.54.tar.gz"
source_sha256 = "480cb7acde46995f716ac0fe983e12e6acaef552248b781cca01563937b90ed1"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.54-any-stack-57bf29a6.tgz"
version = "0.0.54"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "3316c2fb88c0846a86d12cbb7165428d9307a968299250b44d7eabdc237b1491"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.59.tar.gz"
source_sha256 = "142b937a08a3a3b1f4f57194f7ac90a3eb2a8bee1f7804bb3475824dc5cacb62"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.59-any-stack-3316c2fb.tgz"
version = "0.0.59"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.88"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.59"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.88"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.54"
