api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "e9bfb27905fb3b48799eb57d9764d427af2d0fb6fce47b89378eeeff529bf11f"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "f87d08b149377fe75fa533cbfa535a00a82397cd7c2ad10e9fd01dd8048eee7c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.104-any-stack-e9bfb279.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "d8b6445460e5d38c2eb1fffe521d246ffc57faac042b177fb5132211fa97b9bd"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "89e1e311465bd8c8665a185121458912a71744b5d3c233b008cdc8d8a47faa2f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.65-any-stack-d8b64454.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "9babe6a936d4aac8e8ece23758111723b57bd246d932b96a1a2b85369de585e6"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "1c3a4a8df66e607e1158c1c950980e182d6ea3868f8a8eadab056cd829bd1a67"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.70-any-stack-9babe6a9.tgz"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.104"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.104"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.65"
