api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "40f5cefe3db9eaf2f38ae62dfad8eb091bde5cc3c8c76577c2acd732daf59004"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.115.tar.gz"
    source_sha256 = "4c5e9e121df4065300cc43050e1b01277269a88bed5c68207e7ab539ddd43fca"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.115-any-stack-40f5cefe.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "b21d6a28ce80a062bf7ae5a1b15831764c94b7b96ffd0d5b7da4503576d4a6c4"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "b24da0c7af4a782c484655f9c3366581e85ea6f037d53d429bfb5067104f1f03"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.70-any-stack-b21d6a28.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "9ff55f59c56e887f496b9380dd5bd325808d6d3ec0bf6f441f79ac5fbc23608c"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "edf8c14c1655d95ed083519c58bff7a78e4823cc31b230858d864afc4ab1d8ab"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.79-any-stack-9ff55f59.tgz"
    version = "0.0.79"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.115"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.79"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.115"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.70"
