api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "b4a744c41bd0ba0c4e563d47ca9c3d7c413c74a42833a9214ef8c2db24e631f4"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "03c89c1c73722cc7884104a521787e36f8899c7c237eaa9167b1dc18b93cf5fa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.47-any-stack-b4a744c4.tgz"
version = "0.0.47"

[[metadata.dependencies]]
id = "org.cloudfoundry.nodejs-compat"
sha256 = "89b560093ad52be271329123872f5e44d5f81bb70b77baf394acbfe65b66b039"
source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.16.tar.gz"
source_sha256 = "c0878cae7980d20a5d0a3bbfa2e0acb209695ec44bb738bf13da5576f79b16f2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.16-any-stack-89b56009.tgz"
version = "0.0.16"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "9712c7cca53b89ea2fe6acac2292ad4c1fd1060fec6020141240c17d61d9f780"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.25.tar.gz"
source_sha256 = "5d4df2cd4f541cee654736d168c70da35430396be8e807fbad8449661d3ada18"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.25-any-stack-9712c7cc.tgz"
version = "0.0.25"

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs-compat"
optional = true
version = "0.0.16"

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.47"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.25"

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs-compat"
optional = true
version = "0.0.16"

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.47"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.27"
