api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "0e03afe63da014ed1033d2595619a3bd2e86b32604ce2bb7c5cd54862b152a75"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.109.tar.gz"
    source_sha256 = "7322b3a28943d934a0d2e4214efca00e2f6dede76178fd142bee62c6e7b5f613"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.109-any-stack-0e03afe6.tgz"
    version = "0.0.109"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "c2d51bace40b246af780b1fc26996ceaf53f14348a17b6fb49a431e59dea6f5d"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "a4cc33a4b8ea6c95363f137beb1c485d647abf9ed2ec6ce2677bc1e6a81bac24"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.67-any-stack-c2d51bac.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "859b76dcd498d6f622c5652f87b92a98f5061b829adf49cdc6d2e514697cb2d7"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "59f49ad44ae287639ce44e6c862367669868f72b62668e52a5eccaf58c069071"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.73-any-stack-859b76dc.tgz"
    version = "0.0.73"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.109"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.73"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.109"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.67"
