api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "48bb3c7bd9acbadbcb1c1283230768ad6271eca5a9fe7cc9e91e3b8c23aeaba4"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.58.tar.gz"
source_sha256 = "e7fc5459e1f50cac42eb8b4ae53fca73123da9f71c5b409c9281f0507567529b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.58-any-stack-48bb3c7b.tgz"
version = "0.0.58"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "c25ef4298483e2db6718f7acbcbc2a00671799719a7d030a286970b74de0d394"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.35.tar.gz"
source_sha256 = "8b543c24b9d124404a06948f6b6de86ef91f62af87feebf131fa440d89a544a0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.35-any-stack-c25ef429.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "04612667135283ddae52d4a55c8ad819ca9a23eadfe99108262fe6e066e79549"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "006a1fd055858961733e5c58d4143179211cbecd66b53fdad645ddf70e572d83"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.36-any-stack-04612667.tgz"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.58"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.58"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.35"
