api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "6569594c51feb0f572a5a2d15cb6fd80b03bf345fbbfb07a94945a8c91433750"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.79.tar.gz"
source_sha256 = "6faae609955ca9da7e7d41386768e41970a687cf484009b005e46e6cf124ba75"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.79-any-stack-6569594c.tgz"
version = "0.0.79"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "97241451dc1e420ef5a2c21a9b176083ee0395f1d96cb3b313e61e2a004d49c6"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "73a990b6ead6bf27c925578ff3dd41d0d5edd08b8c572a8e136638513a5d6acf"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.48-any-stack-97241451.tgz"
version = "0.0.48"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "8508b9f16d3bcfc54a0ad076350f962d2f71a3a9644d8d3e6a8b3635fcbe994c"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.54.tar.gz"
source_sha256 = "8be9a6e7c62f2c94adc93f48a74c1f12bbad3fad122fd762bd07b5160b3ca971"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.54-any-stack-8508b9f1.tgz"
version = "0.0.54"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.79"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.54"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.79"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.48"
