api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "c05bc8350d324ff8866bc9586bbc5f0de8fbb42093dbf5a56b215776162c6ca1"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.64.tar.gz"
source_sha256 = "4ab4dbe99d82308e3e84248bad8bb0b0f1967b687311aef05cc7fea6534aad31"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.64-any-stack-c05bc835.tgz"
version = "0.0.64"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "aa41466a97f2bf8a0bc5affb150c8cc69e32f1925d7533b9219d7e1988806c09"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "2532396786fc93f2961a9e817552729d1c2aa483f78d7c3ec1d63c8c6dd4d5f5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.41-any-stack-aa41466a.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "2288a6d7829b4d0221bdbb030ab5a625e7dda2c61413c2764972dd1b3bd2f84e"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "9c556e6072704e481c3d8a49152b0ca2302e6140d8ba8ceb453bfbe9c343b30f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.45-any-stack-2288a6d7.tgz"
version = "0.0.45"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.64"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.45"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.64"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.41"
