api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "2d218e47910c5c0176c6316e04695892f16ca57862098cb278c1a6b55dcbb3e9"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.121.tar.gz"
    source_sha256 = "1c55094cdba5cde49ae0b1ab3792ec1194e55a87ad2af51bdd52b9469850f0f7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.121-any-stack-2d218e47.tgz"
    version = "0.0.121"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "05d86bba98b5e4cf268196b68bb3822e62552afc6d3310376fda7e85907e017d"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "88a13c43f1e8f19f8dc28b08c6f1e72ee229da29d7fee4002fa1b63de1a06975"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.73-any-stack-05d86bba.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "bdd0475ad5a1875f4552d6039cc73414af68d220404860a1975227e7c14d4458"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "5bab9a49dbd0e40c79159ebd98c924f0ac14384e6f7c2206150ae35e3c6a8b89"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.81-any-stack-bdd0475a.tgz"
    version = "0.0.81"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.121"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.81"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.121"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.73"
