api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "e0012d41fce4b6e8294c65e48d8daf1f34504be71f1f5eae38bc00ea80696324"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.112.tar.gz"
    source_sha256 = "23ce8176ddd7a39b3e628285e2c50fb2c0c0632a42bb434b59367469fc252648"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.112-any-stack-e0012d41.tgz"
    version = "0.0.112"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "05c44e2f725c89ddeef0d381850a4b3af8ea02d4408848d0495f8d96ccf9dc5a"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "397738bbb3c00a9c11d56e59e2efe099c89d20c0fb8f324417112a1afdb1314c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.69-any-stack-05c44e2f.tgz"
    version = "0.0.69"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "e46c9e0365824948e3ac0799b894f4fe123e4bd2a4cd161ab2ded7d3be5a4cd9"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "cd78a988e6713efa3c864170fe6884b401f9db2b8a99230ce11bb6df75311c09"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.77-any-stack-e46c9e03.tgz"
    version = "0.0.77"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.112"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.77"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.112"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.69"
