api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "46901e43c73a219d910b3ca73603b7454230c2a427992084449be3d5c76542a5"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.69.tar.gz"
source_sha256 = "01dfa289a4e6b1af22b91e84ff35d39713fc1298a9d790420451f26b2ec5f5d6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.69-any-stack-46901e43.tgz"
version = "0.0.69"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "ff4371a58397734742f1e37b030b96cbb92826fc2b11d9ba68a6f06cc98c2601"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.43.tar.gz"
source_sha256 = "43491097562f4c40df4a1470a6eda61e6ab0393b6f62a1e6ae1c1c29482e9f2d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.43-any-stack-ff4371a5.tgz"
version = "0.0.43"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "7ade7b32d4685f6bfde71260b6ac66b39e946a1d4bfcb589ee59df9be08c6272"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "bf94ce9a551151b3a693ed58d3c20b02ae3ad7048286b28ee3b2421a8bf550be"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.48-any-stack-7ade7b32.tgz"
version = "0.0.48"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.69"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.48"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.69"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.43"
