api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "83223798e7092024e04a96cadce08ae777b1c7ab346d7be2526bd8c9bc809d9a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.138.tar.gz"
    source_sha256 = "9237dac0b0af3db3c1861b7f497a8b8e0c90a2f84c224478f6cafd61eadb747a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.138-any-stack-83223798.tgz"
    version = "0.0.138"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "49a9ff6fd238a9f31ef02efe2a6233bca8775b262054b427ff9ee23e11215534"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "5f3d63351a02074e6cf0ebb8678be4f72405f9c39b5d2d20bf07a7ca0c1375ad"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.68-any-stack-49a9ff6f.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "b0cfd5641d935e97fcf891f8db0fec1a9edbe0aec7addeb96cafb759985773b3"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "fad6f7bc83a650a6186c1c79737cf960316a2216382227a80095aed67fecfcce"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.85-any-stack-b0cfd564.tgz"
    version = "0.0.85"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "5cb687dfcb5a21ff8bd1543a2ad790b2da296c40e40348cae7e09e010a85074d"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "995275ee91a581b35243f8c7cfff6aaa747da0cb4b9b81bcd73986610088c0e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.97-any-stack-5cb687df.tgz"
    version = "0.0.97"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.138"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.97"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.138"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.85"
