api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "2be63e8d9bf352dde670330d98538a4abd0265381818bd7833b001faa7925d26"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.63.tar.gz"
source_sha256 = "2d97e6e47f4036f877235cf3cf9b0b326abba6ed949d811a0e6bf18c1f8d7f69"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.63-any-stack-2be63e8d.tgz"
version = "0.0.63"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "aa41466a97f2bf8a0bc5affb150c8cc69e32f1925d7533b9219d7e1988806c09"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "2532396786fc93f2961a9e817552729d1c2aa483f78d7c3ec1d63c8c6dd4d5f5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.41-any-stack-aa41466a.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "16fd794a90d1b62fd4d7f086dc8444a627a8cd728f27d16ab2f10338106f5aa6"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.43.tar.gz"
source_sha256 = "adb892924dbd67dd160989741f7d3ae453c4ce64f54c153958f8d6f1290fa25a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.43-any-stack-16fd794a.tgz"
version = "0.0.43"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.63"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.43"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.63"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.41"
