api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "e0cefb71795acea598d6deda59372f1c99de022771de428573238c2714e42582"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.76.tar.gz"
source_sha256 = "58f2354b878960ac379958c5f7e6ce95e939d8ce3b59d38849290713979c2d2f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.76-any-stack-e0cefb71.tgz"
version = "0.0.76"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "22bc1637007fa7d3134bd0d5c5eeedaee05806a6b9f8c55a003cfcb0527d7c96"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "fd8a4e5788c8912dc1d4ae56261469717f43f63f0cb1db17427b310497440768"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.47-any-stack-22bc1637.tgz"
version = "0.0.47"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "2fad92a173ad56e6519810f8a84128e9aca3e42e8a62e89aa3173d32877fb92c"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.52.tar.gz"
source_sha256 = "296b8cd4d0554c11b3abfbefcfdce8ca6ecb497cd46da855eb9018a4be82eb1b"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.52-any-stack-2fad92a1.tgz"
version = "0.0.52"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.76"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.52"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.76"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.47"
