api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "2a7156761354cfbca8444b29ca959dbf0c51dec7407714283fba909e748f4b9d"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.72.tar.gz"
source_sha256 = "d9208f31b744ed433b9fbb2471fcc924bfc42868cb1fdd467ffeb1ece01a4f0c"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.72-any-stack-2a715676.tgz"
version = "0.0.72"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "6ddfc2cff3db401ea11e1d1b22e2cee2cfc70bd3d4f111cef3e7769f440aa364"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.44.tar.gz"
source_sha256 = "ca89a412e7874d8ce2d59e1d76ed1e9de2eefb62b2a4f6dea3cf9c3d0a59b68d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.44-any-stack-6ddfc2cf.tgz"
version = "0.0.44"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "264dee08c92a35f0983344454e272e6c7c3e015ddf39302ae3f9975e226cfd2e"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.50.tar.gz"
source_sha256 = "244e027b3b8e05c11873743ceda252e48b87e4790544fa4dc57bef8e606e0cad"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.50-any-stack-264dee08.tgz"
version = "0.0.50"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.72"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.50"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.72"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.44"
