api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "46901e43c73a219d910b3ca73603b7454230c2a427992084449be3d5c76542a5"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.69.tar.gz"
source_sha256 = "01dfa289a4e6b1af22b91e84ff35d39713fc1298a9d790420451f26b2ec5f5d6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.69-any-stack-46901e43.tgz"
version = "0.0.69"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "1095d0b28be173bac90c90ec46cab7fa99c3989d19d7811f2a5080e7bcc4aeb9"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "22b6badd1b232c1d7dddc52d775b79983866ee9b14c71ac6cd1e58a89fab936b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.42-any-stack-1095d0b2.tgz"
version = "0.0.42"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "86f7fd987054372fc2e8c59ce6b905e7f4ed96f6c6b62efb5dcaca1db7deb600"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "2b9eed02436aaa29483595d61ac0b26821bf7cdf1fc46fcdddd2dcd0c24aedf8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.47-any-stack-86f7fd98.tgz"
version = "0.0.47"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.69"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.47"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.69"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.42"
