api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "74c6d4e8da4708029216d8c8e1a60d490cd277eab3938ea61348a06e666c2bd4"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.77.tar.gz"
source_sha256 = "3c2a33457f00c0b6488139b578af3d7e7a4a50b103379a1b720d55e34a4eddb4"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.77-any-stack-74c6d4e8.tgz"
version = "0.0.77"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "22bc1637007fa7d3134bd0d5c5eeedaee05806a6b9f8c55a003cfcb0527d7c96"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "fd8a4e5788c8912dc1d4ae56261469717f43f63f0cb1db17427b310497440768"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.47-any-stack-22bc1637.tgz"
version = "0.0.47"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "2fad92a173ad56e6519810f8a84128e9aca3e42e8a62e89aa3173d32877fb92c"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.52.tar.gz"
source_sha256 = "296b8cd4d0554c11b3abfbefcfdce8ca6ecb497cd46da855eb9018a4be82eb1b"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.52-any-stack-2fad92a1.tgz"
version = "0.0.52"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.77"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.52"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.77"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.47"
