api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "986157669040a56bd29e951a48dae95d712aca9a8fb24244d1875c63a2f9037d"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.128.tar.gz"
    source_sha256 = "41daf54f94d02ad529fdea23f962f7096f917853f8be7af49248fdd5a460710a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.128-any-stack-98615766.tgz"
    version = "0.0.128"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "49a9ff6fd238a9f31ef02efe2a6233bca8775b262054b427ff9ee23e11215534"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "5f3d63351a02074e6cf0ebb8678be4f72405f9c39b5d2d20bf07a7ca0c1375ad"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.68-any-stack-49a9ff6f.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "c653d2dd8ff8027f1078565a162d52b26742277fedf5eb7ea03d577c0622f0af"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "2219870bccd2655dba2f12d780765ca4b627ca003ca13759a19ee79e5c2687be"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.78-any-stack-c653d2dd.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "712d5a068ca6db2462b4d7a484a03808f5bf3d0cf8da39c8f7bb9e3541d4d082"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "6e791554dc52586f675fccf9dfa4d080e1bb8360797aaa1de048da42cb46ba25"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.89-any-stack-712d5a06.tgz"
    version = "0.0.89"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.128"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.89"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.128"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.78"
