api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "895c17296e3f4ce463fff574aca5fcebfee0872426a67e4810864abc1d74e586"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.159.tar.gz"
    source_sha256 = "df0fff56568798879231caea1ca1e4a71c3f3ca4b5015f051aee40c99a401818"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.159-any-stack-895c1729.tgz"
    version = "0.0.159"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "820f9023f5f2f043bdc9837bc85b9e81d1b18747c92c03776cf4d57c5ed042f7"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.3.tar.gz"
    source_sha256 = "56caea3405b1ab055cf1b43a393fdf6c0949d8f0191d0972410bab8cc1a8cc81"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.1.3-any-stack-820f9023.tgz"
    version = "0.1.3"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "c486072ee1fcfa5bbccf28df30c5f232b99abc44ff309daf51a4462a4ad54fd9"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.1.4.tar.gz"
    source_sha256 = "13f5ae20aa7ab78c16eff27b9146f2299cd1674db1f753a7c834b419e9d3fa56"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.1.4-any-stack-c486072e.tgz"
    version = "0.1.4"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.159"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.1.4"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.159"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.3"
