api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "a47881f8d725a5507858bdfe647b4f6b136e6724653b5c6b18ea6afdb6333574"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.56.tar.gz"
source_sha256 = "924d5e537da4616b1a4d741a5145e0e431045c70ea66b1439a3b26b484d009e4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.56-any-stack-a47881f8.tgz"
version = "0.0.56"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "07c7a3d5e48190d9c9fa9ccf9b3075f24168105a77f13c5b5f880b178564db4b"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.33.tar.gz"
source_sha256 = "f537dc263c82e0d0731faca7ab8625ceb40d82e6cf9f4af13000cc56785fc518"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.33-any-stack-07c7a3d5.tgz"
version = "0.0.33"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "b4f3c5e5d4cadad70eda49ef5df4750c7b86a201d4fb405f9b4c3a6613da3585"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.32.tar.gz"
source_sha256 = "a38eb7f534931ca7a82892b2c264ae46be4dfba6f12ee322311b92ec0d4e6715"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.32-any-stack-b4f3c5e5.tgz"
version = "0.0.32"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.56"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.32"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.56"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.33"
