api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "110beb9c8751fade550583d91c6019755a5a6a61aee3858eeadeec925943a316"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.61.tar.gz"
source_sha256 = "02ebdf7359060cafeb221a042254def33991c73c82fbc05f5ce781044b878861"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.61-any-stack-110beb9c.tgz"
version = "0.0.61"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "6fa32805e27bba57b1173ee4a938fdedcf9ba9c135ee57b01e72dd01e6d1ed5b"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.39.tar.gz"
source_sha256 = "735cb04576e45caf5d0a615f33ad4b5608ea992c5b9fc6d17c616649d3a90b3c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.39-any-stack-6fa32805.tgz"
version = "0.0.39"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "afd7cab59bbc1fa67986d39497b019074d3a4ce83bc43b0add8ba2d326564726"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "6a4437167ad9565a6de15a164d417575b17af33f35a94d478a0e82a28af34a31"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.41-any-stack-afd7cab5.tgz"
version = "0.0.41"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.61"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.41"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.61"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.39"
