api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "40f5cefe3db9eaf2f38ae62dfad8eb091bde5cc3c8c76577c2acd732daf59004"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.115.tar.gz"
    source_sha256 = "4c5e9e121df4065300cc43050e1b01277269a88bed5c68207e7ab539ddd43fca"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.115-any-stack-40f5cefe.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "05c44e2f725c89ddeef0d381850a4b3af8ea02d4408848d0495f8d96ccf9dc5a"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "397738bbb3c00a9c11d56e59e2efe099c89d20c0fb8f324417112a1afdb1314c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.69-any-stack-05c44e2f.tgz"
    version = "0.0.69"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "285734444d76577109af3314697a35fba4665b635c375a7c9c23908fa58bb358"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "8ab88a9d5956415010c00dd08bbb75090d8904cf39100325c1c0f56503684c7f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.78-any-stack-28573444.tgz"
    version = "0.0.78"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.115"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.78"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.115"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.69"
