api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "507595a26031b1e5bd2f5449a24a1614aaa0dc9b387dabff6c792dc59224ff82"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.147.tar.gz"
    source_sha256 = "8083336eb558c9cdff63869a4d8ff09a60dd573a6e950b591f2e62890e28632c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.147-any-stack-507595a2.tgz"
    version = "0.0.147"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "a4368d8840d295c28f91759976113f4a8d2f1704e41019f22bf92ac9bc460014"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "0d2d0e61ee51182b1faa08942c1394c850c28f3754a5ef5f18edbf36a04ad80d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.87-any-stack-a4368d88.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "5b2ad0ceda4842102eaf31ddc13d2db67fc1de5f10719d8fdc82fae86d09c5e5"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "fe256a0519ff53a5fdd640fed8358f839006e5341aa469ecb671a5e990906211"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.100-any-stack-5b2ad0ce.tgz"
    version = "0.0.100"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.147"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.100"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.147"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.87"
