api = "0.2"

[buildpack]
  id = "org.cloudfoundry.nodejs"
  name = "Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "2b9cea9e9bfc3c9dd4f12e3b1f42b199fd50d68a3fdf85f9346f519973be9d4b"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.158.tar.gz"
    source_sha256 = "09982a99cef8d8b7012ec2ae2afb0fcf12bcb799eaec1593488b8fb95edf1687"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.158-any-stack-2b9cea9e.tgz"
    version = "0.0.158"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "820f9023f5f2f043bdc9837bc85b9e81d1b18747c92c03776cf4d57c5ed042f7"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.3.tar.gz"
    source_sha256 = "56caea3405b1ab055cf1b43a393fdf6c0949d8f0191d0972410bab8cc1a8cc81"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.1.3-any-stack-820f9023.tgz"
    version = "0.1.3"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "8d4a9d253e0d0b0b963fd0708646d5c5eac19fd64b869f965cc89f2009b3ffdb"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.111.tar.gz"
    source_sha256 = "d8d2ef9f167e79eec6b923830f7861fd310e85ef9631991d804df7636b86e704"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.111-any-stack-8d4a9d25.tgz"
    version = "0.0.111"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.158"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.111"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.158"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.3"
