api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "b6c5c7995710c61e49abe2bcb22528fc14a3636737bb3b04d4e3f11ccbec54d1"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.53.tar.gz"
source_sha256 = "e762cc3c8986d5094f9fab4a375b6985b465cbf82e43ef67341cd61855ad7f9a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.53-any-stack-b6c5c799.tgz"
version = "0.0.53"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "07c7a3d5e48190d9c9fa9ccf9b3075f24168105a77f13c5b5f880b178564db4b"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.33.tar.gz"
source_sha256 = "f537dc263c82e0d0731faca7ab8625ceb40d82e6cf9f4af13000cc56785fc518"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.33-any-stack-07c7a3d5.tgz"
version = "0.0.33"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "ce726ebc162e27ea1e6c1188664dff153bb1b08c0cf39d7cf9fc9b98e68943ee"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.31.tar.gz"
source_sha256 = "19fbbb06d9dedafb219954b0a3bc3787b862f7a09279235c28695d4e9ce3306a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.31-any-stack-ce726ebc.tgz"
version = "0.0.31"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.53"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.31"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.53"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.33"
