api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs"
name = "Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "f7ab504f2c2b3ca2fa56f03b447199e7690278f3b063d3ffd2841020cd4813d3"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.51.tar.gz"
source_sha256 = "da96d30a105be4ccee8d51ddf9283630452544ae2a4dbcc06a64be71336102be"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.51-any-stack-f7ab504f.tgz"
version = "0.0.51"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "7cf7624621af8c5f0467cd95c990bc29fbb1a38d6e1847de7dcdf63668440b0b"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.32.tar.gz"
source_sha256 = "804703b70699bc0be458a3c65fa320b8e20666ac48b0da5eb0dd6dd04135d9f9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.32-any-stack-7cf76246.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "dbd045b95ac7dc48ed48b2793db7e7234b7f48553a70ffc2908e3e2d408a9885"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.30.tar.gz"
source_sha256 = "7e79b07b7306995e775dc2813d0f02189610b6a303b2f9011a790f24cf7ec760"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.30-any-stack-dbd045b9.tgz"
version = "0.0.30"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.51"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.30"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.51"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.32"
