api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "2b9cea9e9bfc3c9dd4f12e3b1f42b199fd50d68a3fdf85f9346f519973be9d4b"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.158.tar.gz"
    source_sha256 = "09982a99cef8d8b7012ec2ae2afb0fcf12bcb799eaec1593488b8fb95edf1687"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.158-any-stack-2b9cea9e.tgz"
    version = "0.0.158"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "1e3fe18f0ec6734ecbad66090d4ceaae569d98c187cd47d94909c2384149922f"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "37a58e6b3161b725bcde2fdae8e2ec79dcbf424a3a8f0d4c031e268d186449e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.95-any-stack-1e3fe18f.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "820f9023f5f2f043bdc9837bc85b9e81d1b18747c92c03776cf4d57c5ed042f7"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.3.tar.gz"
    source_sha256 = "56caea3405b1ab055cf1b43a393fdf6c0949d8f0191d0972410bab8cc1a8cc81"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.1.3-any-stack-820f9023.tgz"
    version = "0.1.3"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "bda0664df0515694627794a02f8d9433b35c8a8e67df1f92711ba353f7c477d6"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.1.3.tar.gz"
    source_sha256 = "70c3ba95508d9951f5b0b93b8a04980bb2633150fbc6a6c2761ef34a4a836ea3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.1.3-any-stack-bda0664d.tgz"
    version = "0.1.3"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.95"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.158"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.1.3"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.95"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.158"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.3"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.158"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.1.3"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.158"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.3"
