api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "36758a0b2ff52326bacbed1c5070c93321094f995bab5d020cf469d0c4c6969a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.150.tar.gz"
    source_sha256 = "6631db4ae1eeeb073b334a01a71f8edb435bef8426fe19e96b0c5d7d42609658"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.150-any-stack-36758a0b.tgz"
    version = "0.0.150"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "f9972378988b988df1f03b5ddf557b494723439053b1b0ec77fb487f5b80a2b2"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "01361b2379c8287f81afac227bb9312a42e60e43b17a4800b3c28195773b0cb6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.87-any-stack-f9972378.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "c4daa884f4d4f8c4527a4b6ab8ce07a6f551ac7320bc58f3803c80dba2f67d48"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "209e248f603a3aa30be477d1e5ecc25ce3e9ff1101ef42240f90296a1ed863e3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.90-any-stack-c4daa884.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "40ba3a66f909fdcfd9b265d4c4c3e11489b4c69cde8ee3e8b1781552b19cbfb0"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "c1238a1e1d019ec1e0295f3f646e609c3af5063e9ce7aa1e8ed155a6810eaadc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.105-any-stack-40ba3a66.tgz"
    version = "0.0.105"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.87"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.105"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.87"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.90"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.105"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.90"
