api = "0.2"

[buildpack]
id = "org.shim.nodejs"
name = "CF Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "lifecycle"
version = "0.5.0"
uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","org.cloudfoundry.stacks.cflinuxfs2"]

[[metadata.dependencies]]
id = "org.cloudfoundry.nodejs-compat"
source_sha256 = "5f3d63351a02074e6cf0ebb8678be4f72405f9c39b5d2d20bf07a7ca0c1375ad"
source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.68.tar.gz"
sha256 = "49a9ff6fd238a9f31ef02efe2a6233bca8775b262054b427ff9ee23e11215534"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://github.com/cloudfoundry/nodejs-compat-cnb/releases/download/v0.0.68/nodejs-compat-cnb-0.0.68.tgz"
version = "0.0.68"

[[metadata.dependencies]]
id = "org.cloudfoundry.node-engine"
sha256 = "3d6886e002d41471d723d98a61da443e53ed71ad93496831973675c2bb8d12a4"
source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.124.tar.gz"
source_sha256 = "981572423aefa077a8bb127b6a6d3fd322d5ad1e4ea0cfaba38b61095235c8f3"
stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.124-any-stack-3d6886e0.tgz"
version = "0.0.124"

[[metadata.dependencies]]
id = "org.cloudfoundry.npm"
sha256 = "9fbdc0c70892e6c1296629bf7783854dca16ba8f3427a23c3a81150bca169441"
source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.75.tar.gz"
source_sha256 = "983ff6121c5d3659a3ed47b244e9b4d2b355eb654aff411da3196fff12bab28f"
stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.75-any-stack-9fbdc0c7.tgz"
version = "0.0.75"

[[metadata.dependencies]]
id = "org.cloudfoundry.yarn"
sha256 = "0ee88787b40357ca27355d36d73f19fc7ead0148d5714e47946898e1861af77b"
source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.83.tar.gz"
source_sha256 = "cc5137ea10a358f0246778c9998fc231cd1b7739d12b266737b91b9c6235c64b"
stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.83-any-stack-0ee88787.tgz"
version = "0.0.83"

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs-compat"
version = "0.0.68"

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.124"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.83"

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs-compat"
version = "0.0.68"

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.124"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.75"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.124"

[[order.group]]
id = "org.cloudfoundry.yarn"
version = "0.0.83"

[[order]]

[[order.group]]
id = "org.cloudfoundry.node-engine"
version = "0.0.124"

[[order.group]]
id = "org.cloudfoundry.npm"
version = "0.0.75"
