api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "5abc450423b9a13cf3e8f83623d30cd61081af293e85044a8d6d88e29548cc66"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.7.2/lifecycle-v0.7.2%2Blinux.x86-64.tgz"
    source_sha256 = "5abc450423b9a13cf3e8f83623d30cd61081af293e85044a8d6d88e29548cc66"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.7.2-any-stack-5abc4504.tgz"
    version = "0.7.2"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "e2e7efb6c450eecbc15bfa5e85cb96202a074ce37393a04447c34fe0b49afe7f"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.172.tar.gz"
    source_sha256 = "c7f735bb424366092e14509daa42095e7cd234f27862fed940adfe57db10c99b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine_0.0.172_linux_noarch_any-stack_e2e7efb6.tgz"
    version = "0.0.172"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "51af49632c84feefae3c09b7ce290ac123d7123fcdf2ba13fd652b723b1d9a34"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.1.5.tar.gz"
    source_sha256 = "0db746811a1d5ed3d55a58bb4f5676a6866c81f8b0044aaec9f619b72ae61652"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat_0.1.5_linux_noarch_any-stack_51af4963.tgz"
    version = "0.1.5"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "f7ea6e798ddc2f56a25946334c09c14ddac24a514ffe2aaa8fc886ed75423902"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.5.tar.gz"
    source_sha256 = "11af2cd8810a18b6bec21fab93cb2884a0533b57abd9dd614e64bff81d3dbf52"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.1.5-any-stack-f7ea6e79.tgz"
    version = "0.1.5"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn-install"
    sha256 = "a00b905eae55f54b68e5ff764f2c27a602fd480daa53d04f61c4f2f4bdf78a6a"
    source = "https://github.com/cloudfoundry/yarn-install-cnb/archive/v0.1.15.tar.gz"
    source_sha256 = "5040e7ec7f2c3532382c254750fc8897183b80b90f9a57ed8bfb3ce60cf0d0e4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn-install/org.cloudfoundry.yarn-install_0.1.15_linux_noarch_any-stack_a00b905e.tgz"
    version = "0.1.15"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.1.5"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.172"

  [[order.group]]
    id = "org.cloudfoundry.yarn-install"
    version = "0.1.15"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.1.5"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.172"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.5"
