api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "5abc450423b9a13cf3e8f83623d30cd61081af293e85044a8d6d88e29548cc66"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.7.2/lifecycle-v0.7.2%2Blinux.x86-64.tgz"
    source_sha256 = "5abc450423b9a13cf3e8f83623d30cd61081af293e85044a8d6d88e29548cc66"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.7.2-any-stack-5abc4504.tgz"
    version = "0.7.2"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "fe616060aee70ccd5f7cfa83aca7f0adf5a55d6eae9599f317163fe90ed5ace0"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.177.tar.gz"
    source_sha256 = "0f1f93c7922cc25e0f1deffc0978b8e18d82cb390eb6adb63da6c1c6ad8a21cc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine_0.0.177_linux_noarch_any-stack_fe616060.tgz"
    version = "0.0.177"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "8cd5cb8d003395a876351312c0bc74218dafc844549a47430ef0db2b74a9cd50"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.1.7.tar.gz"
    source_sha256 = "7365e3449ff79462d5df71e78503e7aae42d383d925fa0468653a2b3a708d20d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat_0.1.7_linux_noarch_any-stack_8cd5cb8d.tgz"
    version = "0.1.7"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "46a01cf09e255e2ea19db22250d3dc27f45ed9e9de637ff77a584236e3c87eda"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.10.tar.gz"
    source_sha256 = "d6d6c0d7633e42b8510c19949b369cef3a17b98c6e5381c91a63524c443771ee"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm_0.1.10_linux_noarch_any-stack_46a01cf0.tgz"
    version = "0.1.10"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn-install"
    sha256 = "d6dc674b41bd94a30b315fc48ce8652f3fd356c4719c4749b03c505bee6ca356"
    source = "https://github.com/cloudfoundry/yarn-install-cnb/archive/v0.1.18.tar.gz"
    source_sha256 = "d7f62b747f95d6dcf5f04ba3dfdd8d71dd2250f0e11d104a1da6c618a2f00b58"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn-install/org.cloudfoundry.yarn-install_0.1.18_linux_noarch_any-stack_d6dc674b.tgz"
    version = "0.1.18"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.1.7"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.177"

  [[order.group]]
    id = "org.cloudfoundry.yarn-install"
    version = "0.1.18"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.1.7"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.177"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.10"
