api = "0.2"

[buildpack]
id = "org.shim.nodejs"
name = "CF Node.js Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "lifecycle"
version = "0.5.0"
uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","org.cloudfoundry.stacks.cflinuxfs2"]

[[metadata.dependencies]]
id = "org.cloudfoundry.nodejs-compat"
sha256 = "5451165ebffe9dc78f3831ab74598892863ec1d4be8e0a379b561b442ae06b40"
source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.51.tar.gz"
source_sha256 = "48f3b14780badbca6f92fcfb9081f868bd67864a0161ef836158618098dac4c8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://github.com/cloudfoundry/nodejs-compat-cnb/releases/download/v0.0.51/nodejs-compat-cnb-0.0.51.tgz"
version = "0.0.25"

[[metadata.dependencies]]
id = "org.cloudfoundry.nodejs"
sha256 = "b061f6f3df8bf4f1b060a60878adff82c0be0f2fa1ee9a51a1075f96ef81519e"
source = "https://github.com/cloudfoundry/nodejs-cnb/archive/v0.0.4.tar.gz"
source_sha256 = "c107069e6d59becf21a6870a37c4b8a281ea1d7a56d57bff6bbe27c953168977"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://github.com/cloudfoundry/nodejs-cnb/releases/download/v0.0.4/nodejs-cnb-v0.0.4.tgz"
version = "0.0.4"

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs-compat"
version = "0.0.25"

[[order.group]]
id = "org.cloudfoundry.nodejs"
version = "0.0.4"

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs"
version = "0.0.4"
