api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "3d6886e002d41471d723d98a61da443e53ed71ad93496831973675c2bb8d12a4"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.124.tar.gz"
    source_sha256 = "981572423aefa077a8bb127b6a6d3fd322d5ad1e4ea0cfaba38b61095235c8f3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.124-any-stack-3d6886e0.tgz"
    version = "0.0.124"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "49a9ff6fd238a9f31ef02efe2a6233bca8775b262054b427ff9ee23e11215534"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "5f3d63351a02074e6cf0ebb8678be4f72405f9c39b5d2d20bf07a7ca0c1375ad"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/cloudfoundry/nodejs-compat-cnb/releases/download/v0.0.68/nodejs-compat-cnb-0.0.68.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "a4368d8840d295c28f91759976113f4a8d2f1704e41019f22bf92ac9bc460014"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "0d2d0e61ee51182b1faa08942c1394c850c28f3754a5ef5f18edbf36a04ad80d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.87-any-stack-a4368d88.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "0ee88787b40357ca27355d36d73f19fc7ead0148d5714e47946898e1861af77b"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "cc5137ea10a358f0246778c9998fc231cd1b7739d12b266737b91b9c6235c64b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.83-any-stack-0ee88787.tgz"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.68"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.124"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.68"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.124"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.87"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.124"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.124"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.87"
