api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "af48e5be2ec24cd3d124cdbf2f8573391bf06a5c5bffc57b84af5bd66921a55b"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.152.tar.gz"
    source_sha256 = "1e9d25104ab1c4e6a4e5295c943191f7bf96f8931fd835dd9d5aea926a4b7843"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.152-any-stack-af48e5be.tgz"
    version = "0.0.152"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "764ff2418aa019c98dd8cec8805b6c064bab57611456b12f42c9ea4c353120bf"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "c1600f66c9c18b741ac2e83752dbeb15add5596fe463060811cb531f69e10f29"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.89-any-stack-764ff241.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "b98c1988230e043b5d0618cd69bcff832da91a8f85eb532c4be688c26326f8a6"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "c2813997623a11ac5f3e9d4bf7f72040327befd9b86fe4e37471d1d785e60f82"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.92-any-stack-b98c1988.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "7473cb2be56f6314218ebc9c72e7f86d35013aca72aa9663543e3c423abd44c6"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "94ebd5e34a5511991898ed23b2297ce25278f30605110eb53848763a297fe8b6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.107-any-stack-7473cb2b.tgz"
    version = "0.0.107"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.89"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.152"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.107"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.89"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.152"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.92"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.152"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.107"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.152"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.92"
