api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "36758a0b2ff52326bacbed1c5070c93321094f995bab5d020cf469d0c4c6969a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.150.tar.gz"
    source_sha256 = "6631db4ae1eeeb073b334a01a71f8edb435bef8426fe19e96b0c5d7d42609658"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.150-any-stack-36758a0b.tgz"
    version = "0.0.150"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "d831c4bcae8e84f57769c9fe18b625b3dafd097dc2910a514328c4113097bdab"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "e2e5d2861fdb802c2a70ea6e7d11a2eadbca03eb493a7f59d905b9a479fa1c6b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.86-any-stack-d831c4bc.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "c4daa884f4d4f8c4527a4b6ab8ce07a6f551ac7320bc58f3803c80dba2f67d48"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "209e248f603a3aa30be477d1e5ecc25ce3e9ff1101ef42240f90296a1ed863e3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.90-any-stack-c4daa884.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "36088615e172cdc48aa27e78611f133475b43368fa65fb39648955fcb4023af1"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "61f54ab83e52a6ac8e3b45e013cce58eb0682a03b43516f35117496bc66b9ea7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.104-any-stack-36088615.tgz"
    version = "0.0.104"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.86"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.104"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.86"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.90"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.104"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.90"
