api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "36758a0b2ff52326bacbed1c5070c93321094f995bab5d020cf469d0c4c6969a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.150.tar.gz"
    source_sha256 = "6631db4ae1eeeb073b334a01a71f8edb435bef8426fe19e96b0c5d7d42609658"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.150-any-stack-36758a0b.tgz"
    version = "0.0.150"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "8f79ee5faa9f4bd6d188b60b62b5aa06e8d1d82bfe08f93ee612134d94818c40"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "3f52cf3b90f88171e8cab7ba0d742ce60bd80f5570d2366457c559c0e527cc59"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.83-any-stack-8f79ee5f.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "82c31cbad48613f32034e13c0a9106b9a2bc4a5ed3515da38c009f23c1a097eb"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "331c3cd928e8e0ee4b6f2a87e52b0f4255882e6f26b7456d37e0f1709cb64f61"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.88-any-stack-82c31cba.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "a54832decb9e2a63c048e711ca30780d602b9e8890f7afc342999c12d3632606"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "fdadf468e11e401d76d5668317c94e68b67d862df1546a829a577d009a54bee7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.101-any-stack-a54832de.tgz"
    version = "0.0.101"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.83"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.101"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.83"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.88"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.101"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.88"
