api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "b4e10f0d301d9d7bbbf956b80a2bbaa214ec6fa29e5df7cfa956147e6dd6af58"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.162.tar.gz"
    source_sha256 = "f93023f7030497c534c4db175c43b8085f5c1eb788594499f26cf31fcc1cc7d3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.162-any-stack-b4e10f0d.tgz"
    version = "0.0.162"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "1e3fe18f0ec6734ecbad66090d4ceaae569d98c187cd47d94909c2384149922f"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "37a58e6b3161b725bcde2fdae8e2ec79dcbf424a3a8f0d4c031e268d186449e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.95-any-stack-1e3fe18f.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "820f9023f5f2f043bdc9837bc85b9e81d1b18747c92c03776cf4d57c5ed042f7"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.1.3.tar.gz"
    source_sha256 = "56caea3405b1ab055cf1b43a393fdf6c0949d8f0191d0972410bab8cc1a8cc81"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.1.3-any-stack-820f9023.tgz"
    version = "0.1.3"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn-install"
    sha256 = "c486072ee1fcfa5bbccf28df30c5f232b99abc44ff309daf51a4462a4ad54fd9"
    source = "https://github.com/cloudfoundry/yarn-install-cnb/archive/v0.1.4.tar.gz"
    source_sha256 = "13f5ae20aa7ab78c16eff27b9146f2299cd1674db1f753a7c834b419e9d3fa56"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn-install/org.cloudfoundry.yarn-install-0.1.4-any-stack-c486072e.tgz"
    version = "0.1.4"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.95"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.162"

  [[order.group]]
    id = "org.cloudfoundry.yarn-install"
    version = "0.1.4"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.95"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.162"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.3"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.162"

  [[order.group]]
    id = "org.cloudfoundry.yarn-install"
    version = "0.1.4"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.162"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.1.3"
