api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "eeeebe831c11c19a29ebc14499e06d448a7e2bf200bf2036d9f2193581216f6c"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.149.tar.gz"
    source_sha256 = "559e9efeb0a7ce031efd0f5cc7849e3949a742957aa728b3c71f28f4632d7b8c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.149-any-stack-eeeebe83.tgz"
    version = "0.0.149"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "49a9ff6fd238a9f31ef02efe2a6233bca8775b262054b427ff9ee23e11215534"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "5f3d63351a02074e6cf0ebb8678be4f72405f9c39b5d2d20bf07a7ca0c1375ad"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/cloudfoundry/nodejs-compat-cnb/releases/download/v0.0.68/nodejs-compat-cnb-0.0.68.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "a4368d8840d295c28f91759976113f4a8d2f1704e41019f22bf92ac9bc460014"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "0d2d0e61ee51182b1faa08942c1394c850c28f3754a5ef5f18edbf36a04ad80d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.87-any-stack-a4368d88.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "5b2ad0ceda4842102eaf31ddc13d2db67fc1de5f10719d8fdc82fae86d09c5e5"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "fe256a0519ff53a5fdd640fed8358f839006e5341aa469ecb671a5e990906211"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.100-any-stack-5b2ad0ce.tgz"
    version = "0.0.100"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.68"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.149"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.100"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.68"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.149"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.87"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.149"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.100"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.149"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.87"
