api = "0.2"

[buildpack]
  id = "org.shim.nodejs"
  name = "CF Node.js Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.6.1/lifecycle-v0.6.1%2Blinux.x86-64.tgz"
    source_sha256 = "674a98d9cde0ba55ce500bfea2f6fc454f39591449bfe9d491d8b65a391b9ac6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.6.1-any-stack-674a98d9.tgz"
    version = "0.6.1"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "85e93f4e818ddb0dfc6e4bcf5130291dd6b74c9c4394fc124dda1e9e9851f79f"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.153.tar.gz"
    source_sha256 = "1907503b7d82aff117f9d6fd5f1c42e531337b157093a5525519df1af9f5a5ae"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.153-any-stack-85e93f4e.tgz"
    version = "0.0.153"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nodejs-compat"
    sha256 = "9c1a7fc951b90d0a0d9754f48e951c3f12357edda5a03aa54bc18fe001011d70"
    source = "https://github.com/cloudfoundry/nodejs-compat-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "b41f86b62c2c0ff3a70ec3b37a22426ebc3554ae487405c85f09abd354aa7468"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nodejs-compat/org.cloudfoundry.nodejs-compat-0.0.90-any-stack-9c1a7fc9.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.npm"
    sha256 = "b98c1988230e043b5d0618cd69bcff832da91a8f85eb532c4be688c26326f8a6"
    source = "https://github.com/cloudfoundry/npm-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "c2813997623a11ac5f3e9d4bf7f72040327befd9b86fe4e37471d1d785e60f82"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.npm/org.cloudfoundry.npm-0.0.92-any-stack-b98c1988.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.yarn"
    sha256 = "89e3ecc7619ea73d68e1192f448beb5e91e6b71236d8ddb523500335cf588d89"
    source = "https://github.com/cloudfoundry/yarn-cnb/archive/v0.0.108.tar.gz"
    source_sha256 = "4c84653a17d648b774d64032f185f536ffd1445cc30ef5b7a9023aa83e58dee3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.yarn/org.cloudfoundry.yarn-0.0.108-any-stack-89e3ecc7.tgz"
    version = "0.0.108"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.90"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.153"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.108"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.nodejs-compat"
    version = "0.0.90"

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.153"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.92"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.153"

  [[order.group]]
    id = "org.cloudfoundry.yarn"
    version = "0.0.108"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.153"

  [[order.group]]
    id = "org.cloudfoundry.npm"
    version = "0.0.92"
